// action - account reducer
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_INITIALIZE = 'ACCOUNT_INITIALIZE';
export const FIREBASE_STATE_CHANGED = 'FIREBASE_STATE_CHANGED';

// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const MENU_TYPE = '@customization/MENU_TYPE';
export const PRESET_COLORS = '@customization/PRESET_COLORS';
export const THEME_LOCALE = '@customization/THEME_LOCALE';
export const THEME_RTL = '@customization/THEME_RTL';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const SET_OUTLINED_FILLED = '@customization/SET_OUTLINED_FILLED';

// action - snackbar
export const SNACKBAR_OPEN = '@snackbar/SNACKBAR_OPEN';

// action - cart

export const ADD_PRODUCTS = '@cart/ADD_PRODUCTS';
export const REMOVE_PRODUCT = '@cart/REMOVE_PRODUCT';
export const UPDATE_QUANTITY = '@cart/UPDATE_QUANTITY';
export const NEXT_STEP = '@cart/NEXT_STEP';
export const BACK_STEP = '@cart/BACK_STEP';
export const SET_STEP = '@cart/SET_STEP';
export const SET_BILLING_ADDRESS = '@cart/SET_BILLING_ADDRESS';
export const SET_DISCOUNT = '@cart/SET_DISCOUNT';
export const SET_SHIPPING_CHARGE = '@cart/SET_SHIPPING_CHARGE';
export const SET_PAYMENT_METHOD = '@cart/SET_PAYMENT_METHOD';
export const SET_PAYMENT_CARD = '@cart/SET_PAYMENT_CARD';
export const RESET_CART = '@cart/RESET_CART';

// actions - sections
export const FETCH_SECTION_ATTRIBUTES = '@sections/FETCH_SECTION_ATTRIBUTES';
export const FETCH_ROLE_SECTION_ATTRIBUTES = '@sections/FETCH_ROLE_SECTION_ATTRIBUTES';

/**
 * ################################
 * Review Board Action Types
 * ################################
 */

// CLIENT REFERRAL
export const REVIEW_BOARD_REFERRAL_SET_CLIENT_DECISION = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_CLIENT_DECISION';
export const REVIEW_BOARD_REFERRAL_SET_CLIENT_DETAIL = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_CLIENT_DETAIL';
export const REVIEW_BOARD_REFERRAL_SET_REFERRAL_DETAIL = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_REFERRAL_DETAIL';
export const REVIEW_BOARD_REFERRAL_LIST_CLIENT_REFERRALS = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_LIST_CLIENT_REFERRALS';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_EMP_REFERRAL_REQUEST = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_EMP_REFERRAL_REQUEST';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_SNAT = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_SNAT';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_FACES_SDH = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_FACES_SDH';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_CASE_PRESENTATION = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_CASE_PRESENTATION';


/**
 * ################################
 * Case Managaer Action Types
 * ################################
 */

// DAILY WORKLOAD
export const CASE_MANAGER_SET_DAILY_WORKLOAD_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_DAILY_WORKLOAD_DETAILS';
export const CASE_MANAGER_CREATE_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_CREATE_DAILY_WORKLOAD';
export const CASE_MANAGER_LIST_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_LIST_DAILY_WORKLOAD';
export const CASE_MANAGER_RETRIEVE_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_RETRIEVE_DAILY_WORKLOAD';
export const CASE_MANAGER_UPDATE_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_UPDATE_DAILY_WORKLOAD';


// CLIENT ASSESSMENT
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_CLIENT_STATUS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_CLIENT_STATUS';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_NON_TYPE_DATA = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_NON_TYPE_DATA';

// CLIENT REASSESSMENT
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_REASSESSMENT_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_REASSESSMENT_DETAILS';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_NEWEM_ASSESSMENT_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_NEWEM_ASSESSMENT_DETAILS';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_EXISTINGEM_ASSESSMENT_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_EXISTINGEM_ASSESSMENT_DETAILS';

// ASSESSMENT FORMS - NEW EM
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_PROVIDER_SPECIFIC_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_PROVIDER_SPECIFIC_FORM_UUID';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_GENERAL_ASSESSMENT_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_GENERAL_ASSESSMENT_FORM_UUID';

// ASSESSMENT FORMS - EXISTING EM
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_PROVIDER_SPECIFIC_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_PROVIDER_SPECIFIC_FORM_UUID';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_GENERAL_ASSESSMENT_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_GENERAL_ASSESSMENT_FORM_UUID';

// ASSESSMENT FORMS - REASSESSMENT
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_PROVIDER_SPECIFIC_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_PROVIDER_SPECIFIC_FORM_UUID';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_GENERAL_ASSESSMENT_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_GENERAL_ASSESSMENT_FORM_UUID';
