// action - account reducer
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_INITIALIZE = 'ACCOUNT_INITIALIZE';
export const FIREBASE_STATE_CHANGED = 'FIREBASE_STATE_CHANGED';

// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const MENU_TYPE = '@customization/MENU_TYPE';
export const PRESET_COLORS = '@customization/PRESET_COLORS';
export const THEME_LOCALE = '@customization/THEME_LOCALE';
export const THEME_RTL = '@customization/THEME_RTL';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const SET_OUTLINED_FILLED = '@customization/SET_OUTLINED_FILLED';

// action - snackbar
export const SNACKBAR_OPEN = '@snackbar/SNACKBAR_OPEN';

// action - cart

export const ADD_PRODUCTS = '@cart/ADD_PRODUCTS';
export const REMOVE_PRODUCT = '@cart/REMOVE_PRODUCT';
export const UPDATE_QUANTITY = '@cart/UPDATE_QUANTITY';
export const NEXT_STEP = '@cart/NEXT_STEP';
export const BACK_STEP = '@cart/BACK_STEP';
export const SET_STEP = '@cart/SET_STEP';
export const SET_BILLING_ADDRESS = '@cart/SET_BILLING_ADDRESS';
export const SET_DISCOUNT = '@cart/SET_DISCOUNT';
export const SET_SHIPPING_CHARGE = '@cart/SET_SHIPPING_CHARGE';
export const SET_PAYMENT_METHOD = '@cart/SET_PAYMENT_METHOD';
export const SET_PAYMENT_CARD = '@cart/SET_PAYMENT_CARD';
export const RESET_CART = '@cart/RESET_CART';

// actions - sections
export const FETCH_SECTION_ATTRIBUTES = '@sections/FETCH_SECTION_ATTRIBUTES';
export const FETCH_ROLE_SECTION_ATTRIBUTES = '@sections/FETCH_ROLE_SECTION_ATTRIBUTES';


export const MESSAGING_ADD_NEW_MESSAGE = '@messaging/MESSAGING_ADD_NEW_MESSAGE';
export const MESSAGING_ADD_NEW_MESSAGE_SEND = '@messaging/MESSAGING_ADD_NEW_MESSAGE_SEND';
export const MESSAGING_SET_SEARCH_USERS_LIST = '@messaging/MESSAGING_SET_SEARCH_USERS_LIST';
export const MESSAGING_SET_SEARCH_USERS_LIST_SELECTED = '@messaging/MESSAGING_SET_SEARCH_USERS_LIST_SELECTED';

export const MESSAGING_SET_ACTIVE_MESSAGES_LIST = '@messaging/MESSAGING_SET_ACTIVE_MESSAGES_LIST';
export const MESSAGING_SET_ACTIVE_RECIPIENT_USER = '@messaging/MESSAGING_SET_ACTIVE_RECIPIENT_USER';
export const MESSAGING_SET_ACTIVE_RECIPIENT_HISTORY = '@messaging/MESSAGING_SET_ACTIVE_RECIPIENT_HISTORY';


/**
 * ################################
 * Review Board Action Types
 * ################################
 */

// client REFERRAL
export const REVIEW_BOARD_REFERRAL_SET_CLIENT_DECISION = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_CLIENT_DECISION';
export const REVIEW_BOARD_REFERRAL_SET_CLIENT_DETAIL = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_CLIENT_DETAIL';
export const REVIEW_BOARD_REFERRAL_SET_REFERRAL_DETAIL = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_REFERRAL_DETAIL';
export const REVIEW_BOARD_REFERRAL_LIST_CLIENT_REFERRALS = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_LIST_CLIENT_REFERRALS';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_EMP_REFERRAL_REQUEST = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_EMP_REFERRAL_REQUEST';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_SNAT = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_SNAT';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_FACES_SDH = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_FAMILIAR_FACES_FACES_SDH';
export const REVIEW_BOARD_REFERRAL_SET_FORM_FILE_CASE_PRESENTATION = '@REVIEW_BOARD/REVIEW_BOARD_REFERRAL_SET_FORM_FILE_CASE_PRESENTATION';


/**
 * ################################
 * Case Managaer Action Types
 * ################################
 */

// DAILY WORKLOAD
export const CASE_MANAGER_SET_DAILY_WORKLOAD_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_DAILY_WORKLOAD_DETAILS';
export const CASE_MANAGER_CREATE_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_CREATE_DAILY_WORKLOAD';
export const CASE_MANAGER_LIST_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_LIST_DAILY_WORKLOAD';
export const CASE_MANAGER_RETRIEVE_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_RETRIEVE_DAILY_WORKLOAD';
export const CASE_MANAGER_UPDATE_DAILY_WORKLOAD = '@CASE_MANAGER/CASE_MANAGER_UPDATE_DAILY_WORKLOAD';
export const CASE_MANAGER_SET_RETRIEVED_DAILY_WORKLOAD_DETAILS_UPDATE = '@CASE_MANAGER/CASE_MANAGER_SET_RETRIEVED_DAILY_WORKLOAD_DETAILS_UPDATE';
export const CASE_MANAGER_SET_ADD_DAILY_WORKLOAD_DATE = '@CASE_MANAGER/CASE_MANAGER_SET_ADD_DAILY_WORKLOAD_DATE';
export const CASE_MANAGER_RESET_DAILY_WORKLOAD_DETAILS = '@CASE_MANAGER/CASE_MANAGER_RESET_DAILY_WORKLOAD_DETAILS';


// client ASSESSMENT
export const CASE_MANAGER_LIST_CLIENT_ASSESSMENT_FOR_CASE_MANAGER = '@CASE_MANAGER/CASE_MANAGER_LIST_CLIENT_ASSESSMENT_FOR_CASE_MANAGER';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_CLIENT_STATUS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_CLIENT_STATUS';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_CLIENT_DETAIL = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_CLIENT_DETAIL';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_CASEMANAGER_DETAIL = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_CASEMANAGER_DETAIL';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_NON_TYPE_DATA = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_NON_TYPE_DATA';
// client REASSESSMENT
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_REASSESSMENT_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_REASSESSMENT_DETAILS';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_NEWEM_ASSESSMENT_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_NEWEM_ASSESSMENT_DETAILS';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_EXISTINGEM_ASSESSMENT_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_EXISTINGEM_ASSESSMENT_DETAILS';
// ASSESSMENT FORMS - NEW EM
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_PROVIDER_SPECIFIC_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_PROVIDER_SPECIFIC_FORM_UUID';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_GENERAL_ASSESSMENT_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_NEWEM_GENERAL_ASSESSMENT_FORM_UUID';
// ASSESSMENT FORMS - EXISTING EM
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_PROVIDER_SPECIFIC_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_PROVIDER_SPECIFIC_FORM_UUID';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_GENERAL_ASSESSMENT_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_GENERAL_ASSESSMENT_FORM_UUID';
// ASSESSMENT FORMS - REASSESSMENT
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_PROVIDER_SPECIFIC_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_PROVIDER_SPECIFIC_FORM_UUID';
export const CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_GENERAL_ASSESSMENT_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_GENERAL_ASSESSMENT_FORM_UUID';
export const CASE_MANAGER_SET_RETRIEVED_CLIENT_ASSESSMENT_DATA = '@CASE_MANAGER/CASE_MANAGER_SET_RETRIEVED_CLIENT_ASSESSMENT_DATA';


// Case Manager - Client Intervention
export const CASE_MANAGER_SET_CLIENT_INTERVENTION_DETAILS = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_INTERVENTION_DETAILS';
export const CASE_MANAGER_SET_CLIENT_INTERVENTION_CLIENT_DETAIL = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_INTERVENTION_CLIENT_DETAIL';
export const CASE_MANAGER_SET_CLIENT_INTERVENTION_CASEMANAGER_DETAIL = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_INTERVENTION_CASEMANAGER_DETAIL';
export const CASE_MANAGER_SET_CLIENT_INTERVENTION_DATE_ADD = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_INTERVENTION_DATE_ADD';
export const CASE_MANAGER_SET_CLIENT_INTERVENTION_FORM_UUID = '@CASE_MANAGER/CASE_MANAGER_SET_CLIENT_INTERVENTION_FORM_UUID';
export const CASE_MANAGER_LIST_CLIENT_INTERVENTION_FOR_CASE_MANAGER = '@CASE_MANAGER/CASE_MANAGER_LIST_CLIENT_INTERVENTION_FOR_CASE_MANAGER';


// client - PERSONAL INFORMATION
export const CLIENT_SET_PERSONAL_INFORMATION_DETAIL = '@client/CLIENT_SET_PERSONAL_INFORMATION_DETAIL';
export const CLIENT_SET_HOME_SAFETY_ASSESSMENT_DETAIL = '@client/CLIENT_SET_PERSONAL_INFORMATION_DETAIL';
export const CLIENT_SET_RETRIEVED_PERSONAL_INFORMATION_DATA = '@client/CLIENT_SET_RETRIEVED_PERSONAL_INFORMATION_DATA';
export const CLIENT_SET_VISITOR_LOG_DETAIL = '@client/CLIENT_SET_VISITOR_LOG_DETAIL';
export const CLIENT_SET_COMMUNICATION_LOG_DETAIL = '@client/CLIENT_SET_COMMUNICATION_LOG_DETAIL';

// Client - Clinical Information
export const CLIENT_SET_CLINICAL_INFORMATION_DETAIL = '@client/CLIENT_SET_CLINICAL_INFORMATION_DETAIL';
export const CLIENT_SET_RETRIEVED_CLINICAL_INFORMATION_DATA = '@client/CLIENT_SET_RETRIEVED_CLINICAL_INFORMATION_DATA';



/**
 * ################################
 * Clinician Action Types
 * ################################
 */

// DAILY WORKLOAD
export const CLINICIAN_SET_DAILY_WORKLOAD_DETAILS = '@CLINICIAN/CLINICIAN_SET_DAILY_WORKLOAD_DETAILS';
export const CLINICIAN_CREATE_DAILY_WORKLOAD = '@CLINICIAN/CLINICIAN_CREATE_DAILY_WORKLOAD';
export const CLINICIAN_LIST_DAILY_WORKLOAD = '@CLINICIAN/CLINICIAN_LIST_DAILY_WORKLOAD';
export const CLINICIAN_RETRIEVE_DAILY_WORKLOAD = '@CLINICIAN/CLINICIAN_RETRIEVE_DAILY_WORKLOAD';
export const CLINICIAN_UPDATE_DAILY_WORKLOAD = '@CLINICIAN/CLINICIAN_UPDATE_DAILY_WORKLOAD';
export const CLINICIAN_SET_RETRIEVED_DAILY_WORKLOAD_DETAILS_UPDATE = '@CLINICIAN/CLINICIAN_SET_RETRIEVED_DAILY_WORKLOAD_DETAILS_UPDATE';
export const CLINICIAN_SET_ADD_DAILY_WORKLOAD_DATE = '@CLINICIAN/CLINICIAN_SET_ADD_DAILY_WORKLOAD_DATE';
export const CLINICIAN_RESET_DAILY_WORKLOAD_DETAILS = '@CLINICIAN/CLINICIAN_RESET_DAILY_WORKLOAD_DETAILS';


// CLIENT ASSESSMENT
export const CLINICIAN_LIST_CLIENT_ASSESSMENT_FOR_CLINICIAN = '@CLINICIAN/CLINICIAN_LIST_CLIENT_ASSESSMENT_FOR_CLINICIAN';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_CLIENT_STATUS = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_CLIENT_STATUS';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_CLIENT_DETAIL = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_CLIENT_DETAIL';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_CLINICIAN_DETAIL = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_CLINICIAN_DETAIL';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_NON_TYPE_DATA = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_NON_TYPE_DATA';
// client REASSESSMENT
export const CLINICIAN_SET_CLIENT_ASSESSMENT_REASSESSMENT_DETAILS = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_REASSESSMENT_DETAILS';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_NEWEM_ASSESSMENT_DETAILS = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_NEWEM_ASSESSMENT_DETAILS';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_EXISTINGEM_ASSESSMENT_DETAILS = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_EXISTINGEM_ASSESSMENT_DETAILS';
// ASSESSMENT FORMS - NEW EM
export const CLINICIAN_SET_CLIENT_ASSESSMENT_SET_NEWEM_PROVIDER_SPECIFIC_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_SET_NEWEM_PROVIDER_SPECIFIC_FORM_UUID';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_SET_NEWEM_GENERAL_ASSESSMENT_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_SET_NEWEM_GENERAL_ASSESSMENT_FORM_UUID';
// ASSESSMENT FORMS - EXISTING EM
export const CLINICIAN_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_PROVIDER_SPECIFIC_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_PROVIDER_SPECIFIC_FORM_UUID';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_GENERAL_ASSESSMENT_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_SET_EXISTINGEM_GENERAL_ASSESSMENT_FORM_UUID';
// ASSESSMENT FORMS - REASSESSMENT
export const CLINICIAN_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_PROVIDER_SPECIFIC_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_PROVIDER_SPECIFIC_FORM_UUID';
export const CLINICIAN_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_GENERAL_ASSESSMENT_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_ASSESSMENT_SET_REASSESSMENT_GENERAL_ASSESSMENT_FORM_UUID';
export const CLINICIAN_SET_RETRIEVED_CLIENT_ASSESSMENT_DATA = '@CLINICIAN/CLINICIAN_SET_RETRIEVED_CLIENT_ASSESSMENT_DATA';

// Client intervention 
export const CLINICIAN_SET_CLIENT_INTERVENTION_DETAILS = '@CLINICIAN/CLINICIAN_SET_CLIENT_INTERVENTION_DETAILS';
export const CLINICIAN_SET_CLIENT_INTERVENTION_CLIENT_DETAIL = '@CLINICIAN/CLINICIAN_SET_CLIENT_INTERVENTION_CLIENT_DETAIL';
export const CLINICIAN_SET_CLIENT_INTERVENTION_CLINICIAN_DETAIL = '@CLINICIAN/CLINICIAN_SET_CLIENT_INTERVENTION_CLINICIAN_DETAIL';
export const CLINICIAN_SET_CLIENT_INTERVENTION_DATE_ADD = '@CLINICIAN/CLINICIAN_SET_CLIENT_INTERVENTION_DATE_ADD';
export const CLINICIAN_SET_CLIENT_INTERVENTION_FORM_UUID = '@CLINICIAN/CLINICIAN_SET_CLIENT_INTERVENTION_FORM_UUID';
export const CLINICIAN_LIST_CLIENT_INTERVENTION_FOR_CLINICIAN = '@CLINICIAN/CLINICIAN_LIST_CLIENT_INTERVENTION_FOR_CLINICIAN';



/**
 * ################################
 * External Partner Action Types
 * ################################
 */
export const EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_CLIENT_DETAIL = '@EXTERNAL_PARTNER/EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_CLIENT_DETAIL';
export const EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_EXTERNAL_PARTNER_DETAIL = '@EXTERNAL_PARTNER/EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_EXTERNAL_PARTNER_DETAIL';
export const EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_DATE_ADD = '@EXTERNAL_PARTNER/EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_DATE_ADD';
export const EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_DETAILS = '@EXTERNAL_PARTNER/EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_DETAILS';
export const EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_FORM_UUID = '@EXTERNAL_PARTNER/EXTERNAL_PARTNER_SET_CLIENT_INTERVENTION_FORM_UUID';
export const EXTERNAL_PARTNER_LIST_CLIENT_INTERVENTION_FOR_EXTERNAL_PARTNER = '@EXTERNAL_PARTNER/EXTERNAL_PARTNER_LIST_CLIENT_INTERVENTION_FOR_EXTERNAL_PARTNER';


/**
 * Dashboard Actions - All User Types
 */
export const DASHBOARD_SET_INTERNAL_REFERRAL_DATA = '@DASHBOARD/DASHBOARD_SET_INTERNAL_REFERRAL_DATA';
export const DASHBOARD_SET_EXTERNAL_REFERRAL_DATA = '@DASHBOARD/DASHBOARD_SET_EXTERNAL_REFERRAL_DATA';
export const DASHBOARD_SET_INTERNAL_FOLLOWUP_DATA = '@DASHBOARD/DASHBOARD_SET_INTERNAL_FOLLOWUP_DATA';
export const DASHBOARD_SET_EXTERNAL_FOLLOWUP_DATA = '@DASHBOARD/DASHBOARD_SET_EXTERNAL_FOLLOWUP_DATA';


export const SHARE_SET_INTERNAL_REFERRAL_DATA = '@SHARE/SHARE_SET_INTERNAL_REFERRAL_DATA';
export const SHARE_SET_EXTERNAL_REFERRAL_DATA = '@SHARE/SHARE_SET_EXTERNAL_REFERRAL_DATA';

export const SHARE_SET_INTERNAL_FOLLOWUP_DATA = '@SHARE/SHARE_SET_INTERNAL_FOLLOWUP_DATA';
export const SHARE_SET_EXTERNAL_FOLLOWUP_DATA = '@SHARE/SHARE_SET_EXTERNAL_FOLLOWUP_DATA';


/**
 * Application User Search
 */
export const SET_APPLICATION_USER_SEARCH_LIST = '@SEARCH/SET_APPLICATION_USER_SEARCH_LIST';
export const SET_APPLICATION_USER_SEARCH_PARAMS = '@SEARCH/SET_APPLICATION_USER_SEARCH_PARAMS';